# Generated by Django 4.2.16 on 2024-12-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disasterzone',
            old_name='name',
            new_name='name_zone',
        ),
    ]
