# Generated by Django 4.2.16 on 2024-11-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agency', 'Cơ quan chức năng'), ('citizen', 'Người dân'), ('resource', 'Cơ quan quản lý vật tư')], max_length=10),
        ),
    ]
