# Generated by Django 4.2.16 on 2024-11-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agency', 'Cơ quan cứu nạn cứu hộ'), ('citizen', 'Người dân'), ('authority', 'Cơ quan quản lý vật tư')], max_length=10),
        ),
    ]
