# Generated by Django 4.2.16 on 2024-12-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasternews',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
