# Generated by Django 4.2.16 on 2024-12-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField()),
                ('region', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='DisasterNews',
        ),
    ]
