# Generated by Django 4.2.16 on 2024-12-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='id_card',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
