# Generated by Django 4.2.16 on 2024-12-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ và Tên')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số Điện Thoại')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Khu Vực')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày Đăng Ký')),
            ],
        ),
    ]
