# Generated by Django 4.2.16 on 2024-12-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='region',
            new_name='address',
        ),
    ]
