# Generated by Django 4.2.16 on 2024-12-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_region_subscription_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='name',
            new_name='full_name',
        ),
    ]
