# Generated by Django 4.2.16 on 2024-11-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_group',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('All', 'All')], default='Citizen', max_length=50),
        ),
    ]
