# Generated by Django 4.2.16 on 2024-11-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_target_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_group',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='agency',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
