# Generated by Django 4.2.16 on 2024-11-27 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In Progress', 'Đang tiến hành'), ('Completed', 'Hoàn thành')], default='In Progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('availability_status', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_assigned', models.PositiveIntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.assignment')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_assignment', models.CharField(max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.assignment')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity_needed', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Đang xử lý'), ('Dispatched', 'Đã điều phối'), ('Completed', 'Hoàn thành')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_personnel',
            field=models.ManyToManyField(through='resources.PersonnelAssignment', to='resources.personnel'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_resources',
            field=models.ManyToManyField(through='resources.ResourceAssignment', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.dispatchrequest'),
        ),
    ]
