# Generated by Django 4.2.16 on 2024-11-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrequest',
            name='unit',
            field=models.CharField(default='units', max_length=50),
        ),
    ]
