# Generated by Django 4.2.16 on 2024-11-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resourceassignment_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='province_or_city',
            field=models.CharField(default='Province', max_length=255),
        ),
    ]
