# Generated by Django 4.2.16 on 2024-11-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_province_or_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='quantity',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='personnelassignment',
            name='quantity_assigned',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
