# Generated by Django 4.2.16 on 2024-12-01 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_remove_resourceassignment_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_personnel',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_resources',
        ),
        migrations.CreateModel(
            name='ResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_assigned', models.PositiveIntegerField()),
                ('unit', models.CharField(default='units', max_length=50)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.assignment')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_assignment', models.CharField(max_length=100)),
                ('quantity_assigned', models.PositiveIntegerField(default=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.assignment')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_personnel',
            field=models.ManyToManyField(related_name='assignments', through='resources.PersonnelAssignment', to='resources.personnel', verbose_name='Assigned Personnel'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_resources',
            field=models.ManyToManyField(related_name='assignments', through='resources.ResourceAssignment', to='resources.resource', verbose_name='Assigned Resources'),
        ),
    ]
